//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Employee
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("First Name:")]
        [Required(ErrorMessage ="Employee First Name is Required!")]
        [StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Employee Last Name is Required!")]
        [StringLength(50, MinimumLength = 2)]
        [DisplayName("Last Name:")]
        public string LastName { get; set; }

        [DisplayName("Middle Name:")]
        public string MiddleName { get; set; }
        [Required(ErrorMessage = "Employee Address is Required!")]
        [StringLength(250, MinimumLength = 2)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Employee Salary is Required!")]
        [Range(1000, 1000000000, ErrorMessage = "Salary must be between 1000 and 1000000000")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:c}")]
        public Nullable<decimal> Salary { get; set; }

        [DisplayName("Email Address:")]
        [Required(ErrorMessage ="Employee Email address is Required!")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [RegularExpression(@"[a-zA-Z0-9._]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}", ErrorMessage ="This is not a valid email address!")]
        public string Email { get; set; }
    }
}
